name: test
on:
  push:
    branches:
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v3
      - name: cahe
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-front-${{ hashFiles('./frontend/package-lock.json') }}
      - name: npm ci
        run: cd ./frontend && npm ci
      - name: lint
        run: cd ./frontend && npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v3
      - name: cahe
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-front-${{ hashFiles('./frontend/package-lock.json') }}
      - name: npm ci
        run: cd ./frontend && npm ci
      - name: build
        run: cd ./frontend && npm run build
      - name: ls
        run: cd ./frontend && ls
  